name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches: [ "main" ]

  # GitHub Actions tab থেকে ম্যানুয়ালি রান করার জন্য
  workflow_dispatch:

# GitHub Pages-এ Deploy করার জন্য প্রয়োজনীয় Permissions
permissions:
  contents: read
  pages: write
  id-token: write

# একটির বেশি একই Deployment যেন একই সাথে না চলে
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # ১. সাইট বিল্ড করার Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Jekyll Container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  # ২. GitHub Pages-এ অটোমেটিক লাইভ করার Job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4